### ISSUE TITLE
Missing index.html

### ISSUE THREAD

**Issue by guosim** [the-road-to-learn-react/react-context-example#3]
I get this error when running `npm start`

```
Could not find a required file.
  Name: index.html
  Searched in: C:\Users\hewu\desktop\react-context-example-master\public
```

**Comment by rwieruch** [comment]
My bad! Should be fixed now: https://github.com/the-road-to-learn-react/react-context-example/commit/9ab4e348f4af27694e63070852b81b2d8e0fa49c
